//
// Created by _rayhan on 4/27/23.
//

#ifndef QUESTION__02_FROM_EYE_IN_THE_SKY_TO_CARGO_TRANSPORT__CREATING_A_VERSATILE_UAV_UAV_H
#define QUESTION__02_FROM_EYE_IN_THE_SKY_TO_CARGO_TRANSPORT__CREATING_A_VERSATILE_UAV_UAV_H


class UAV {


public:

    static void takeOff();

    static void land();

};


#endif //QUESTION__02_FROM_EYE_IN_THE_SKY_TO_CARGO_TRANSPORT__CREATING_A_VERSATILE_UAV_UAV_H
